apiVersion: v1
kind: Secret
metadata:
  name: bitnami-overlay
type: Opaque
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind":"Composition","metadata":{"name":"xpostgresqlinstances.bitnami.database.tanzu.vmware.com"}}), missing_ok=True
    ---
    spec:
      pipeline:
      #@overlay/match by=overlay.map_key("step")
      - step: patch-and-transform
        input:
          resources:
          #@overlay/match by=overlay.map_key("name")
          - name: release
            base:
              spec:
                forProvider:
                  values:
                    primary:
                      #@overlay/match missing_ok=True
                      #@overlay/match-child-defaults missing_ok=True
                      persistentVolumeClaimRetentionPolicy:
                        enabled: true
                        whenDeleted: Delete
                    #@overlay/match missing_ok=True
                    #@overlay/match-child-defaults missing_ok=True
                    readReplicas:
                      persistentVolumeClaimRetentionPolicy:
                        enabled: true
                        whenDeleted: Delete
